# From Scipy Docs -- (scipy.linalg)

In [6]:
import scipy
scipy.__version__

'1.2.1'

In [4]:
from scipy import linalg
import numpy as np
a = np.array([[1,3,5],[2,5,1],[2,3,8]])
a

array([[1, 3, 5],
       [2, 5, 1],
       [2, 3, 8]])

In [43]:
linalg.inv(a)

array([[-1.48,  0.36,  0.88],
       [ 0.56,  0.08, -0.36],
       [ 0.16, -0.12,  0.04]])

In [45]:
a.dot(linalg.inv(a))

array([[ 1.00000000e+00, -1.11022302e-16, -5.55111512e-17],
       [ 3.05311332e-16,  1.00000000e+00,  1.87350135e-16],
       [ 2.22044605e-16, -1.11022302e-16,  1.00000000e+00]])

# Solving linear system

In [47]:
a = np.array([[1,3,5],[2,5,1],[2,3,8]])
b = np.array([[10],[8],[3]])
linalg.inv(a).dot(b)   # slow

array([[-9.28],
       [ 5.16],
       [ 0.76]])

In [52]:
a.dot(linalg.inv(a).dot(b)) - b  # a(a^-1.b)-b =[0]  ->slow
a.dot(np.linalg.solve(a,b))-b    # fast 

array([[ 0.00000000e+00],
       [ 0.00000000e+00],
       [-1.77635684e-15]])

In [49]:
# the best and fast way two to system of linear eqn
np.linalg.solve(a,b)

array([[-9.28],
       [ 5.16],
       [ 0.76]])

In [53]:
# find determinent 
linalg.det(a)

-25.000000000000004

In [21]:
#linalg.norm(a)      # sqrt(summation of |aij|^2)
#linalg.norm(a,'fro')  # this are same as previous
#linalg.norm(a,1)     #  L1 norm (max column sum)
#linalg.norm(a,np.inf) # L inf norm (max row sum)
#linalg.norm(a,-1)     # min column sum
linalg.norm(a,-2)

0.5329105309489518

In [8]:
print(a)

[[1 3 5]
 [2 5 1]
 [2 3 8]]
