In [1]:
import numpy as np
print(np.__version__)

1.16.2


In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.full((3,3),True,dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [12]:
arr = np.arange(10)
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [15]:
arr = np.arange(10)
arr[arr%2==1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [22]:
arr = np.arange(10)
out  = np.where(arr%2 ==1,-1,arr)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [28]:
arr.reshape(5,-1)   # -1 =>automatic decide 

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [36]:
#8. How to stack two arrays vertically?
#sol:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)  
# Method 1:
np.concatenate([a,b],axis = 0)  # axis = 1 for horizontali
# Method 2:
np.vstack([a,b])    # hstack => horizontali
# Method 3:
np.r_[a, b]   # r =>row and c=>column

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [46]:
# Common item 
a = np.array(range(10))
b = np.array(range(6,16))
np.intersect1d(a,b)  # one d


array([6, 7, 8, 9])

In [47]:
# From 'a' remove all of 'b'
np.setdiff1d(a,b)

array([0, 1, 2, 3, 4, 5])

In [52]:
#Q. Get the positions where elements of a and b match
a = np.array([1,2,3,3,4,5,5])
b = np.array([1,2,2,3,7,5,8])
np.where(a==b)

(array([0, 1, 3, 5]),)

In [53]:
#Get all items between 5 and 10 from a.

a = np.arange(15)

# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]
#> (array([6, 9, 10]),)

# Method 3: (thanks loganzk!)
a[(a >= 5) & (a <= 10)]

array([ 5,  6,  7,  8,  9, 10])

In [55]:
def maxx(x,y):
    if x>=y:
        return x
    else :
        return y
pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6, 7, 9, 8, 9, 7, 5])

In [65]:
#How to swap two columns in a 2d numpy array?

#Input
arr = np.arange(9).reshape(3,3)
#Solution
arr[:,[1,0,2]]   # column 0 1


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [66]:
#How to swap two row in a 2d numpy array?
arr = np.arange(9).reshape(3,3)
arr[[1,0,2],:]  # row 0,1

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [67]:
#How to reverse the rows of a 2D array?
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [69]:
# Column reverse 
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [86]:
#Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

arr = np.arange(9).reshape(3,3)
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
u_arr = np.random.uniform(low=5,high=10,size=(5,3))
np.set_printoptions(precision = 6)
print(rand_arr)
print(u_arr)

#rand_arr[:4]

[[8.826248 9.527029 6.612289]
 [8.041533 7.320541 7.709331]
 [8.6296   9.404448 5.715573]
 [8.979595 9.712755 8.876434]
 [9.116143 8.419631 6.511319]]
[[8.009972 7.663234 9.943243]
 [5.008777 8.998342 8.55188 ]
 [5.645181 8.056525 7.938814]
 [5.045299 6.48515  6.591013]
 [5.431643 7.08558  5.087786]]


In [225]:
np.random.seed(8)
rand_arr = np.random.random([3,3])/1e3

np.set_printoptions(suppress=True, precision=6)
print(rand_arr)

[[0.000873 0.000969 0.000869]
 [0.000531 0.000233 0.000011]
 [0.00043  0.000402 0.000523]]


# use of                ------  random.seed() 

In [5]:

import random
for i in range(5):
    random.seed(10)
    for i in range(5):
        print(random.random())
    print()

0.5714025946899135
0.4288890546751146
0.5780913011344704
0.20609823213950174
0.81332125135732

0.5714025946899135
0.4288890546751146
0.5780913011344704
0.20609823213950174
0.81332125135732

0.5714025946899135
0.4288890546751146
0.5780913011344704
0.20609823213950174
0.81332125135732

0.5714025946899135
0.4288890546751146
0.5780913011344704
0.20609823213950174
0.81332125135732

0.5714025946899135
0.4288890546751146
0.5780913011344704
0.20609823213950174
0.81332125135732



In [10]:
# Limit the number of items printed in python numpy array a to a maximum of 6 elements.
np.set_printoptions(threshold=6)  # for oppsite=> np.set_printoptions(threshold=np.nan)
a = np.arange(15)
print(a)

[ 0  1  2 ... 12 13 14]


In [15]:
np.set_printoptions()
url = 'iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
iris[:3]  # print 3 row

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [17]:
specific_row = np.array([row[4] for row in iris])
specific_row[:5]
#print(specific_row)

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S15')

In [22]:
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

5.843333333333334 5.8 0.8253012917851409


# How to compute the softmax score?

In [23]:
sepallength = np.array([float(row[0]) for row in iris])

def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

print(softmax(sepallength))

[0.00221959 0.00181724 0.00148783 ... 0.00900086 0.006668   0.00493978]


In [26]:
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
np.percentile(sepallength, q=[5, 95])
#> array([ 4.6  ,  7.255])

array([4.6  , 7.255])

In [34]:
#Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

url = 'iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
print(iris_2d)
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
iris_2d[condition]

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 ...
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]


array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [ ]:
#Q. Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d

In [49]:
url = 'iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.corrcoef(iris_2d[:,0],iris_2d[:,2])[0,1]

0.8717541573048714

In [50]:
#Find out if iris_2d has any missing values.
np.isnan(iris_2d).any()

False

In [ ]:
# Replace all ccurrences of nan with 0 in numpy array

In [56]:
iris_2d [np.isnan(iris_2d)] =0
iris_2d[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       ...,
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [ ]:
# Find the unique values and the count of unique values in iris's species

In [58]:
# Import iris keeping the text column intact
url = 'iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Solution
# Extract the species column as an array
species = np.array([row.tolist()[4] for row in iris])

# Get the unique values and the counts
np.unique(species, return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'), array([50, 50, 50]))

In [73]:
# add a new column in a 2d array
# Input
url = 'iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution
# Compute volume
sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')
volume = (np.pi * petallength * (sepallength**2))/3

# Introduce new dimension to match iris_2d's
volume = volume[:, np.newaxis]

# Add the new column
out = np.hstack([iris_2d, volume])

# View
out[:2]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa',
        38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa',
        35.200498485922445]], dtype=object)

# How to convert a PIL image to numpy array?

In [84]:

from io import BytesIO
from PIL import Image
import PIL, requests

# Import image from URL
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
response = requests.get(URL)

# Read it as Image
I = Image.open(BytesIO(response.content))

# Optionally resize
I = I.resize([750,520])

# Convert to numpy array
arr = np.asarray(I)
print(arr)
# Optionaly Convert it back to an image and show
im = PIL.Image.fromarray(np.uint8(arr))
Image.Image.show(im)

[[[  9  72 125]
  [  9  72 125]
  [  9  72 125]
  ...
  [ 42 103 147]
  [ 43 104 148]
  [ 43 104 148]]

 [[  9  72 125]
  [  9  72 125]
  [  9  72 125]
  ...
  [ 42 103 147]
  [ 43 104 148]
  [ 43 104 148]]

 [[  9  72 125]
  [  9  72 125]
  [  9  72 125]
  ...
  [ 42 103 147]
  [ 43 104 148]
  [ 43 104 148]]

 ...

 [[ 27  51  63]
  [ 27  51  63]
  [ 29  55  68]
  ...
  [ 27  64  91]
  [ 22  57  85]
  [ 22  57  85]]

 [[ 18  45  56]
  [ 18  45  56]
  [ 20  48  62]
  ...
  [ 12  48  74]
  [ 11  45  72]
  [ 11  45  72]]

 [[ 18  45  56]
  [ 18  45  56]
  [ 20  48  62]
  ...
  [ 12  48  74]
  [ 11  45  72]
  [ 11  45  72]]]
